[book]
authors = ["Pylyv"]
language = "en"
multilingual = true
src = "src"
title = "Canyon"

[output.html]
site-url = "/mdBook/"

[preprocessor.toc]
max-level = 2
command = "mdbook-toc"
renderer = ["html"]